export const stateOptions = [
  { label: "- Select State -", name: "selectState", value: "" },
  { label: "Alabama", name: "alabama", value: "AL" },
  { label: "Alaska", name: "alaska", value: "AK" },
  { label: "Arizona", name: "arizona", value: "AZ" },
  { label: "Arkansas", name: "arkansas", value: "AR" },
  { label: "California", name: "california", value: "CA" },
  { label: "Colorado", name: "colorado", value: "CO" },
  { label: "Connecticut", name: "connecticut", value: "CT" },
  { label: "Delaware", name: "delaware", value: "DE" },
  { label: "Florida", name: "florida", value: "FL" },
  { label: "Georgia", name: "georgia", value: "GA" },
  { label: "Hawaii", name: "hawaii", value: "HI" },
  { label: "Idaho", name: "idaho", value: "ID" },
  { label: "Illinois", name: "illinois", value: "IL" },
  { label: "Indiana", name: "indiana", value: "IN" },
  { label: "Iowa", name: "iowa", value: "IA" },
  { label: "Kansas", name: "kansas", value: "KS" },
  { label: "Kentucky", name: "kentucky", value: "KY" },
  { label: "Louisiana", name: "louisiana", value: "LA" },
  { label: "Maine", name: "maine", value: "ME" },
  { label: "Maryland", name: "maryland", value: "MD" },
  { label: "Massachusetts", name: "massachusetts", value: "MA" },
  { label: "Michigan", name: "michigan", value: "MI" },
  { label: "Minnesota", name: "minnesota", value: "MN" },
  { label: "Mississippi", name: "mississippi", value: "MS" },
  { label: "Missouri", name: "missouri", value: "MO" },
  { label: "Montana", name: "montana", value: "MT" },
  { label: "Nebraska", name: "nebraska", value: "NE" },
  { label: "Nevada", name: "nevada", value: "NV" },
  { label: "New Hampshire", name: "new hampshire", value: "NH" },
  { label: "New Jersey", name: "new jersey", value: "NJ" },
  { label: "New Mexico", name: "new mexico", value: "NM" },
  { label: "New York", name: "new york", value: "NY" },
  { label: "North Carolina", name: "north carolina", value: "NC" },
  { label: "North Dakota", name: "north dakota", value: "ND" },
  { label: "Ohio", name: "ohio", value: "OH" },
  { label: "Oklahoma", name: "oklahoma", value: "OK" },
  { label: "Oregon", name: "oregon", value: "OR" },
  { label: "Pennsylvania", name: "pennsylvania", value: "PA" },
  { label: "Rhode Island", name: "rhode island", value: "RI" },
  { label: "South Carolina", name: "south carolina", value: "SC" },
  { label: "South Dakota", name: "south dakota", value: "SD" },
  { label: "Tennessee", name: "tennessee", value: "TN" },
  { label: "Texas", name: "texas", value: "TX" },
  { label: "Utah", name: "utah", value: "UT" },
  { label: "Vermont", name: "vermont", value: "VT" },
  { label: "Virginia", name: "virginia", value: "VA" },
  { label: "Washington", name: "washington", value: "WA" },
  { label: "West Virginia", name: "west virginia", value: "WV" },
  { label: "Wisconsin", name: "wisconsin", value: "WI" },
  { label: "Wyoming", name: "wyoming", value: "WY" },
];

export const DROPDOWN_OPTIONS_MAP = {
  state: stateOptions,
  title: [
    { label: "- Select Title -", name: "selectTitle", value: "" },
    { label: "Mr.", name: "Mr.", value: "Mr." },
    { label: "Ms.", name: "Ms.", value: "Ms." },
    { label: "Mrs.", name: "Mrs.", value: "Mrs." },
    { label: "Dr.", name: "Dr.", value: "Dr." },
  ],
  phoneType: [
    { label: "- Select Type -", name: "selectType", value: "" },
    { label: "Mobile", name: "mobile", value: "cell" },
    { label: "Landline", name: "landline", value: "home" },
  ],
  maritalStatus: [
    { label: "- Select Status -", name: "selectType", value: "" },
    { label: "Single", name: "single", value: "single" },
    { label: "Married", name: "married", value: "married" },
  ],
  leaseTerm: [
    { label: "- Select Term -", name: "selectType", value: "" },
    { label: "12 Months", name: "12months", value: "12" },
    { label: "24 Months", name: "24months", value: "24" },
  ],
  extendedLeaseTerm: [
    { label: "- Select Term -", name: "selectType", value: "" },
    { label: "12 Months", name: "12months", value: "12" },
    { label: "13 Months", name: "13months", value: "13" },
    { label: "14 Months", name: "14months", value: "14" },
    { label: "15 Months", name: "15months", value: "15" },
    { label: "16 Months", name: "16months", value: "16" },
    { label: "17 Months", name: "17months", value: "17" },
    { label: "18 Months", name: "18months", value: "18" },
    { label: "19 Months", name: "19months", value: "19" },
    { label: "20 Months", name: "20months", value: "20" },
    { label: "21 Months", name: "21months", value: "21" },
    { label: "22 Months", name: "22months", value: "22" },
    { label: "23 Months", name: "23months", value: "23" },
    { label: "24 Months", name: "24months", value: "24" },
  ],
  relationship: [
    { label: "- Select Relationship -", name: "selectRelationship", value: "" },
    { label: "Husband", name: "Husband", value: "Husband" },
    { label: "Wife", name: "Wife", value: "Wife" },
    { label: "Son", name: "son", value: "Son" },
    { label: "Daughter", name: "Daughter", value: "Daughter" },
    { label: "Friend", name: "Friend", value: "Friend" },
    { label: "Other", name: "Other", value: "Other" },
  ],
  emergencyContactPhoneType: [
    { label: "- Select Type -", name: "selectType", value: "" },
    { label: "Mobile", name: "mobile", value: "mobile" },
    { label: "Landline", name: "mobile", value: "landline" },
  ],
  employmentStatus: [
    { label: "- Select Status -", name: "selectType", value: "" },
    { label: "Employed", name: "employed", value: "employed" },
    { label: "Retired", name: "retired", value: "retired" },
    { label: "Student", name: "student", value: "student" },
    { label: "Never employed", name: "neverEmployed", value: "neverEmployed" },
    { label: "Other", name: "other", value: "other" },
  ],
  incomeSourceOptions: [
    { label: "- Select Status -", name: "selectType", value: "" },
    { label: "Retirement", name: "retirement", value: "retirement" },
    { label: "Child support", name: "childSupport", value: "childSupport" },
    {
      label: "Commissions / bonuses",
      name: "commissionsBonuses",
      value: "commissionsBonuses",
    },
    {
      label: "Unemployment income",
      name: "unemploymentIncome",
      value: "unemploymentIncome",
    },
    {
      label: "Social security or VA benefits",
      name: "socialSecurityVABenefits",
      value: "socialSecurityVABenefits",
    },
    {
      label: "Scholarship and grant",
      name: "scholarshipGrant",
      value: "scholarshipGrant",
    },
    { label: "Other", name: "other", value: "other" },
  ],
  animalType: [
    { label: "- Select Type -", name: "selectType", value: "" },
    { label: "Dog", name: "Dog", value: "Dog" },
    { label: "Cat", name: "Cat", value: "Cat" },
    { label: "Bird", name: "Bird", value: "Bird" },
    { label: "Other", name: "Other", value: "Other" },
  ],
  applicantType: [
    { label: "- Select Type -", name: "selectType", value: "" },
    { label: "Roommate", name: "roommate", value: "roommate" },
    { label: "Spouse", name: "spouse", value: "spouse" },
    { label: "Guarantor", name: "guarantor", value: "guarantor" },
    { label: "Other", name: "other", value: "other" },
  ],
  accountType: [
    { label: "- Select Type -", name: "selectType", value: "" },
    { label: "Checking", name: "checking", value: "checking" },
    { label: "Savings", name: "savings", value: "savings" },
  ],
};
