import dotenv from "dotenv";

dotenv.config();

export const serverSideVariables = {
  CUSTOMER_SERVICE_URL: process.env.CUSTOMER_SERVICE_URL,
  LEASING_APPLICATION_SERVICE_URL: process.env.LEASING_APPLICATION_SERVICE_URL,
  LEASING_APPLICATION_WEB_URL: process.env.LEASING_APPLICATION_WEB_URL,
  PLS_URL: process.env.PLS_URL,
  ADDRESS_HEADER: process.env.ADDRESS_HEADER,
  XFF_DEPTH: process.env.XFF_DEPTH,
  DD_API_KEY: process.env.DD_API_KEY,
  DD_ENV: process.env.DD_ENV,
  DD_SERVICE: process.env.DD_SERVICE,
  DD_VERSION: process.env.APP_VERSION,
};

export const clientSideVariables = {
  VITE_CUSTOMER_PROFILE_URL: process.env.VITE_CUSTOMER_PROFILE_URL,
  VITE_CUSTOMER_WEBSITE_URL: process.env.VITE_CUSTOMER_WEBSITE_URL,
  VITE_DATADOG_SITE: process.env.VITE_DATADOG_SITE,
  VITE_DD_RUM_ENABLED: process.env.VITE_DD_RUM_ENABLED,
  VITE_DD_APPLICATION_ID: process.env.VITE_DD_APPLICATION_ID,
  VITE_DD_CLIENT_TOKEN: process.env.VITE_DD_CLIENT_TOKEN,
  VITE_DD_ENV: process.env.VITE_DD_ENV,
  VITE_DD_REPLAY_SAMPLE_RATE: process.env.VITE_DD_REPLAY_SAMPLE_RATE,
  VITE_DD_SAMPLE_RATE: process.env.VITE_DD_SAMPLE_RATE,
  VITE_DD_TRACK_INTERACTIONS: process.env.VITE_DD_TRACK_INTERACTIONS,
  VITE_GOOGLE_TAG_MANAGER_AUTH: process.env.VITE_GOOGLE_TAG_MANAGER_AUTH,
  VITE_GOOGLE_TAG_MANAGER_ENABLED: process.env.VITE_GOOGLE_TAG_MANAGER_ENABLED,
  VITE_GOOGLE_TAG_MANAGER_ID: process.env.VITE_GOOGLE_TAG_MANAGER_ID,
  VITE_GOOGLE_TAG_MANAGER_PREVIEW_ID:
    process.env.VITE_GOOGLE_TAG_MANAGER_PREVIEW_ID,
  VITE_INVH_DOMAIN: process.env.VITE_INVH_DOMAIN,
  VITE_DD_VERSION: process.env.APP_VERSION,
};

export const variables = {
  ...serverSideVariables,
  ...clientSideVariables,
};
